version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: agendamento-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendamento
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agendamento-network

volumes:
  postgres_data:
    name: agendamento-postgres-data

networks:
  agendamento-network:
    name: agendamento-network
    driver: bridge